### ISSUE TITLE
Tweaks to Story So Far

### ISSUE THREAD

**Issue by mattodd** [StructuralGenomicsConsortium/CNP18-DENVRdrp-VirtualScreen#1]
Hi @RebeckaIsaksson - some small tweaks to [Story So Far](https://github.com/StructuralGenomicsConsortium/CNP18-DENVRdrp-VirtualScreen/wiki/The-Story-So-Far) page. Close this issue when wiki has been altered.

Do you have anything else (e.g. decks, figures, methods) about the identification of the green site? I see the slide, but feel like it'd benefit from a little extra explanation. I'm assuming we need some tech details from @kipUNC around what was done?

The 150 commercials and the 64 eventuals - are they listed somewhere? Excel?

What happened to the 50 "de novos"? No takers?

2023-11-16 Picogreen - could you try to find a protocol we can share, and can you identify the person who did the screen, and hence who deserves the credit? Can you upload the output of this screen somewhere? Ditto for the subsequent phenotypic assay - protocol and data and credit.

2023-12-11 update - could you post somewhere the compounds that were identified and ordered around the 3 hits?

The pictures are good for humans, and you're using RA numbers to ID the compounds. We should think how best to manage machine readability. Google can't find any of these structures, but could if we had SMILES/InChI etc. I guess we can either add these into relevant issues, long hand, or have an openly-available sheet somewhere with key data. To be discussed with the rest of the team, I guess, and whatever we do should be minimal extra work.

(Actually, on the front page of the repo "life chemicals" is mentioned, but that's a typo, right?)

**Comment by ahsgc** [comment]
@RebeckaIsaksson please update the numbers as follows for DENV VS:

1. HIDDEN GEM nominated 996 Enamine compounds
2. Clustering and manual filtering selected 73 compounds
3. 65 were synthesized by Enamine and submitted for screening

**Comment by RebeckaIsaksson** [comment]
Updates done, structures added, layout improved
